<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWenTvPx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWenTvPx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWenTvPx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWenTvPx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWenTvPx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WenTvPx',
    'container.build_id' => 'ba390bcb',
    'container.build_time' => 1690963566,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWenTvPx');
